name: Lab 7

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: WAD-Lab7-main

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 22
          cache: gradle

      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Run backend tests
        env:
          MY_SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}
        run: ./gradlew test

      - name: Run Jacoco report
        env:
          MY_SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}
        run: ./gradlew jacocoTestReport